### PR TITLE
A little Graphical User Interface

### PR DESCRIPTION
**Pull request by erfanpaslar**
Hi, I created GUI for your sudoku solver.
I used a python library called `Eel` and it helps connect js with python!
also, I explained it a little on [my website](https://letscode.erfanpaslar.ir/post.php?pId=16) and I'd like to use this as an example.

Hope you like it.

P.S. I think my code formatter accidentally modified the  README.md file. 😬

### CODE REVIEW

**Comment by LiorSinai** [comment]
Hi Erfan,

Neat UI! Thank you for choosing my solver to be your backend. I have only recently started learning JavaScript, and this is good motivation to continue!

I like the UI and I am considering accepting your pull request. However, I would like you to add one feature first. Could you have a visual clue between user input numbers and computer generated numbers? E.g. different colours?

See for example https://sudokuspoiler.azurewebsites.net/ .
 
Kind regards,
Lior

**Comment by erfanpaslar** [comment]
Yes i will work on it ✌️

**Comment by erfanpaslar** [comment]
Hi again.
I did the user input numbers and computer generated numbers color.
I added an icon too.

**Comment by LiorSinai** [comment]
Awesome, looks good. I'll merge it into the main branch and do some clean up.

I'm also going to give you a mention on my blog post :)

**Comment by erfanpaslar** [comment]
Thanks a lot 😀

**Pull request merged**
